version: '3.7'
services:
  tf:
    image: hashicorp/terraform:0.13.0
    volumes:
      - .:/infra
    working_dir: /infra
    environment:
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}

# networks:
#   default:
#     external:
#       name: alternate_network